version: '3'
services:
  axelor:
    image: axelor/aio-base
    build: .
    ports:
      - 8080:8080
      - 5433:5432
    volumes:
      - ./volumes/var/lib/postgresql:/var/lib/postgresql
      - ./volumes/var/log/postgresql:/var/log/postgresql
      - ./volumes/var/lib/tomcat:/var/lib/tomcat
      - ./volumes/var/log/tomcat:/var/log/tomcat

